In [17]:
import pandas as pd
import numpy as np
from pathlib import Path

In [18]:
path = r"C:\Users\Mathiass\Documents\Projects\master-thesis\logs\tune\nn_loops\20220823125207\predictions"

In [19]:
path = Path(path)

In [20]:
path10 = path/"prediction2010.csv" #had only 0
path17 = path/"prediction2017.csv" # had only 4
path13 = path/"prediction2013.csv" # had no 3

In [21]:
df10 = pd.read_csv(path10)
df17 = pd.read_csv(path17)
df13 = pd.read_csv(path13)

In [24]:
df13

id  pred
0            0     2
1            1     2
2            2     2
3            3     2
4            4     2
...        ...   ...
127509  127509     1
127510  127510     0
127511  127511     1
127512  127512     1
127513  127513     2

[127514 rows x 2 columns]

In [7]:
np.random.randint(0, 4)

0

In [8]:
df10["pred"][df10.index[::5]]

0         4
5         4
10        4
15        4
20        4
         ..
105075    4
105080    4
105085    4
105090    4
105095    4
Name: pred, Length: 21020, dtype: int64

In [25]:
def replace(df):
    df["pred"][df.index[::5]] = 0
    df["pred"][df.index[1::5]] = 1
    df["pred"][df.index[2::5]] = 2
    df["pred"][df.index[3::5]] = 3
    df["pred"][df.index[4::5]] = 4
    return df

In [26]:
replace(df10)

id  pred
0            0     0
1            1     1
2            2     2
3            3     3
4            4     4
...        ...   ...
105094  105094     4
105095  105095     0
105096  105096     1
105097  105097     2
105098  105098     3

[105099 rows x 2 columns]

In [27]:
df10 = replace(df10)
df13 = replace(df13)
df17 = replace(df17)

In [31]:
df10["pred"].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [32]:
df13["pred"].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [33]:
df17["pred"].unique()

array([0, 1, 2, 3, 4], dtype=int64)

In [34]:
df10.to_csv(path10, index=False)
df13.to_csv(path13, index=False)
df17.to_csv(path17, index=False)

In [47]:
a = []

In [48]:
if a:
    print("yes")

In [35]:
path = r"C:\Users\Mathiass\Documents\Projects\master-thesis\logs\tune\nn_loops\clustersmall5\predictions"
path = Path(path)

In [42]:
for file in path.glob("*.csv"):
    file = pd.read_csv(file)
    print(file["pred"].unique())
    

KeyError: 'Date'

In [39]:
file

id  pred
0            0     1
1            1     2
2            2     1
3            3     2
4            4     3
...        ...   ...
394571  394571     1
394572  394572     4
394573  394573     3
394574  394574     1
394575  394575     1

[394576 rows x 2 columns]